server:
  port: 9006
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  application:
    name: leadnews-comment
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
  data:
    mongodb:
      host: 192.168.200.130
      port: 27017
      database: leadnews-comment
  redis:
    host: 192.168.200.130
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 5000
ribbon:
  ReadTimeout: 5000 # 读取超时时长
  ConnectTimeout: 2000 # 建立链接的超时时长
