server:
  port: 9005
spring:
  application:
    name: leadnews-behavior
  data:
    mongodb:
      host: 192.168.200.130
      port: 27017
      database: leadnews-behavior
  redis:
    host: 192.168.200.130
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
