server:
  port: 9003
spring:
  application:
    name: leadnews-article
  kafka:
    bootstrap-servers: 192.168.200.130:9092
    consumer:
      group-id: ${spring.application.name}-kafka-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.130:8848
    alibaba:
      seata:
        tx-service-group: heima_leadnews_tx_group
  freemarker:
    cache: false  #关闭模板缓存，方便测试
    settings:
      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
    suffix: .ftl               #指定Freemarker模板文件的后缀名
    template-loader-path: classpath:/templates/
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.200.130:3306/leadnews_article?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
# 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  # 设置别名包扫描路径，通过该属性可以给包中的类注册别名
  type-aliases-package: com.heima.model.article.pojos
  global-config:
    datacenter-id: 1
    workerId: 1
#OSS配置
file:
  oss:
    bucket-name: hmtt130lmf
    access-key-id: LTAI5tNWWBdYDfeddvaJF3aZ
    access-key-secret: vulnJ1yDT4eBlCIEDveIXZnXLep3VV
    endpoint: oss-cn-shanghai.aliyuncs.com
    web-site: https://hmtt130lmf.oss-cn-shanghai.aliyuncs.com/   #
    proxy-username: aliyun-sdk-java
    socket-timeout: 10000
    idle-connection-time: 10000
    connection-request-timeout: 4000
    max-connections: 2048
    max-error-retry: 5
    white-list: 127.0.0.1
    connection-timeout: 10000
    prefix: material
  minio:
    accessKey: minio
    secretKey: minio123
    bucket: hmtt130
    endpoint: http://192.168.200.130:9090/
    realPath: http://192.168.200.130:9090/
